# wrangler.toml
name = "gemini-balance"
main = "main:app" # Looks for the 'app' variable in the 'main.py' file
compatibility_date = "2024-05-01"

[build]
command = "pip install -r requirements.txt"
